### ISSUE TITLE
Fix waitForFinalization as in the current version it doesn't go over 0

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/eth2-merge-kurtosis-module#157]
Tried using Pari's input from discord

```yaml
participants:
- elType: geth
  elImage: ethereum/client-go:v1.10.25
  clType: lighthouse
  clImage: sigp/lighthouse:v3.1.2
- elType: geth
  elImage: ethereum/client-go:v1.10.25
  clType: lighthouse
  clImage: sigp/lighthouse:v3.1.2
- elType: nethermind
  elImage: nethermind/nethermind:1.14.3
  clType: teku
  clImage: consensys/teku:22.9.1
- elType: besu
  elImage: hyperledger/besu:22.7.6
  clType: lodestar
  clImage: chainsafe/lodestar:v1.1.0
network:
  networkId: '3151908'
  depositContractAddress: '0x4242424242424242424242424242424242424242'
  secondsPerSlot: 12
  slotsPerEpoch: 32
  altairForkEpoch: 0
  mergeForkEpoch: 0
  totalTerminalDifficulty: 0
  numValidatorKeysPerNode: 64
  preregisteredValidatorKeysMnemonic: giant issue aisle success illegal bike spike
    question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy
    very lucky have athlete
waitForMining: false
waitForFinalization: true
waitForVerifications: true
verificationsEpochLimit: 5
logLevel: info
```

![image](https://user-images.githubusercontent.com/6670312/201639976-ab854ba2-c273-4442-825d-913cebe33205.png)

In the Starlark version this stayed at 0 for a while and never went over 0
