### ISSUE TITLE
Migrate this repo completely to the Starlark version

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/eth2-merge-kurtosis-module#158]
Requires:
[ ] Ensuring the Starlark version ( https://github.com/kurtosis-tech/eth2-module ) has complete parity with the old version, and works
[ ] Building the ability to execute Starlark modules directly from Github, without needing to clone them first
[ ] Showing @parithosh how to use the Starlark version
[ ] Migrating everything in the README to the new one
[ ] Waiting for a couple weeks, to shake out any issues
[ ] Deprecating this repo and pointing it to the Starlark one

**Comment by h4ck3rk3y** [comment]
[ ] Use the new Starlark version in the https://github.com/kurtosis-tech/examples

**Comment by h4ck3rk3y** [comment]
```
participants:
  - elType: geth
    elImage: ethereum/client-go:v1.10.26
    clType: lighthouse
    clImage: sigp/lighthouse:v3.2.1
  - elType: geth
    elImage: ethereum/client-go:v1.10.26
    clType: lighthouse
    clImage: sigp/lighthouse:v3.2.1
  - elType: geth
    elImage: ethereum/client-go:v1.10.26
    clType: lighthouse
    clImage: sigp/lighthouse:v3.2.1
network:
  networkId: '3151908'
  depositContractAddress: '0x4242424242424242424242424242424242424242'
  secondsPerSlot: 12
  slotsPerEpoch: 32
  altairForkEpoch: 0
  mergeForkEpoch: 0
  totalTerminalDifficulty: 0
  numValidatorKeysPerNode: 64
  preregisteredValidatorKeysMnemonic: giant issue aisle success illegal bike spike
    question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy
    very lucky have athlete
waitForMining: false
waitForFinalization: true
waitForVerifications: false
logLevel: info
```
test against the following input (snake case it)
